search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAACJWYQEAAAAAJ8L97yf%2FLbDoTTQLW77TcQLT8HQ%3D7GqMszwYUwK8lx8GFuhROYpIym8AyWQB0t6e7pEBeSbBBjTgny
azure:
  subscription_key: dd9edb553ad6407cadfd24acd47d01a8
